version: "3.3"
services:
  api:
    image: image-retrieval
    container_name: fastapi_app
    build: .
    command: "uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"

  app:
    image: image-retrieval
    container_name: streamlit_app
    build: .
    command: "streamlit run --server.port 8501 --server.enableCORS false streamlit_app.py"
    ports:
      - "8501:8501"
